### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by jimmybrenes** [Darksonn/telnet-chat#1]
Hi

I wonder, How Can I test the chat? I was able to build the chat and enable the telnet, but I don't how I can test the chat. 

Thanks

**Comment by Darksonn** [comment]
You can use a normal telnet client to connect to the server. On my Linux machine, it comes built in as the `telnet` command.

**Comment by An010299** [comment]
What's need for me? How?

**Comment by Darksonn** [comment]
Nothing is needed here.
